config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace 'api' do
    resources :calendars
  end
  post '/sign_in', to: 'home#sign_in'
  delete '/sign_out', to: 'home#sign_out'
  get '/calendar', to: 'home#calendar'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/controllers/api/calendars_controller.rb
module Api
  class CalendarsController < ApplicationController

    def index
      @events = Calendar.order(created_at: :desc)
      render json: { status: 'Success', message: 'All Events', data: @events }, status: :ok
    end

    def create
      @event = Calendar.new(calendar_params)
      respond_to do |format|
        if @event.save
          format.html { redirect_to calendar_path, notice: 'Event Saved!'}
          format.json { render :show, status: :created, location: @event }
        else
          format.html {redirect_to calendar_path, notice: 'Event Not Saved!'}
          format.json { render json: @event.errors, status: :unprocessable_entity }
        end
      end
    end

    def show
      @event = Calendar.find(params[:id])
      render json: { status: 'Success', message: "Loaded Event #{@event.id}", data: @event }, status: :ok
    end

    # Did not get to implement in UI/UX
    def update
      @event = Calendar.find(params[:id])
      if @event.update_attributes(calendar_params)
        render json: { status: 'Success', message: 'Event Updated!', data: @event }, status: :ok
      else
        render json: { status: 'Error', message: 'Event Not Updated!', data: @event.errors }, status: :unprocessable_entity
      end
    end

    # Did not get to implement in UI/UX
    def destroy
      @event = Calendar.find(params[:id])
      @event.destroy
      render json: { status: 'Success', message: 'Deleted Event', data: @event }, status: :ok
    end

    private
    def calendar_params
      params.require(:calendar).permit(:title, :body, :location, :start_time, :end_time)
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # prevent cross-site forgery attacks
  protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate, :except => [:index, :sign_in]

  def index
  end

  def sign_in
    if params[:username] == 'username' && params[:password] == 'password'
      session[:login] = true
      flash[:success] = 'You Successfully Logged In !'
      redirect_to action: 'calendar'
    elsif params[:username] != 'username' && params[:password] != 'password'
      flash[:warning] = 'Incorrect Username or Password !'
      redirect_to action: 'index'
    end
  end

  def sign_out
    logout
  end

  def calendar
    # Make today dynamic so we can switch months in the view
    @today = params[:date] ? Date.parse(params[:date]) : Date.today
    # First day is the first Sunday that includes the beginning of the month
    first_day = @today.beginning_of_month.beginning_of_week
    # Last day is the last Saturday that includes the end of the month
    last_day = @today.end_of_month.end_of_week
    # Weeks is an array of arrays, each of length 7, which contain full weeks i.e. Sun-Sat
    @weeks = (first_day..last_day).to_a.in_groups_of(7)
    # Events by date is all events ordered by start time
    @events_by_date = Calendar.all.order(:start_time)
    # Event is used in our form for to create a new calendar event
    @event = Calendar.new
  end


  
  private
  # Checks if user is logged in, otherwise, redirects back to the root path and prompts user to log in.
  def authenticate
    if session[:login] == true
      true
    else
      flash[:warning] = 'Please Log In !'
      redirect_to action: 'index'
    end
  end

  # Set session to nothing, logging the user out
  def logout
    session[:login] = nil
    flash[:success] = 'You successfully logged out'
    redirect_to action: 'index'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/calendar.html.erb
<%= link_to 'Sign Out', sign_out_path, method: :delete %>
<br>
<div class="row">
  <div class="offset-m2 m10 center-align">
    <h2 id="month">
    <%= link_to '<', date: @today.prev_month %>
    <%= @today.strftime('%B %Y') %>
    <%= link_to '>', date: @today.next_month %>
    </h2>
    <table>
      <thead>
        <tr>
          <th>Sun</th>
          <th>Mon</th>
          <th>Tues</th>
          <th>Wed</th>
          <th>Thurs</th>
          <th>Fri</th>
          <th>Sat</th>
        </tr>
      </thead>

      <tbody>
      <% @weeks.each do |week| %>
        <tr>
        <% week.each do |day| %>
          <td data-target="modal1" class="modal-trigger">
            <div class="hide-scroll">
              <span class="cal-days"><%= day.strftime('%-m/%-d') %></span>
              <% @events_by_date.each do |event| %>
                <ul>
                  <% if event.start_time == day || (day > event.start_time && day <= event.end_time) %>
                    <% @single_event = Calendar.find(event.id) %>
                    <li><span class="single-event"><%= event.title %></span></li>
                  <% end %>
                </ul>
              <% end %>
            </div>
          </td>
        <% end %>
        </tr>
      <% end %>
      </tbody>
      
    </table>

    <!-- Modal Structure -->
    <div id="modal1" class="modal">
      <div class="modal-content">
        <h4>Add Event</h4>
        <p>
          <%= form_for @event, :url => api_calendars_path, method: :create do |f| %>
            <%= f.text_field :title, placeholder: "Title", class: 'event-title' %>
            <%= f.text_field :body, placeholder: "Description", class: 'event-description' %>
            <%= f.text_field :location, placeholder: "Location", class: 'event-location' %>
            <%= f.label :start_time, "Start Date & End Date" %>
            <%= f.date_select(:start_time, :order => [:month, :day], :default => Date.today, use_two_digit_numbers: true, :discard_year => true, class: 'event-start')%>
            <%= f.label :end_time, "End Date" %>
            <%= f.date_select(:end_time, :order => [:month, :day], :default => Date.today, use_two_digit_numbers: true, :discard_year => true, class: 'event-end')%>
            <div>
            <%= f.submit "Submit", class: "btn btn-primary add-event-button" %>
            </div>
          <% end %>
        </p>
      </div>
      <div class="modal-footer">
        <button class="modal-close waves-effect btn-flat">Close</button>
      </div>
    </div>
  
  </div>
</div>

app/views/home/index.html.erb
<div class="Sign_Form">

  <h1>Sign In</h1>
  <%= form_tag("/sign_in", method: "post") do %>
    <%= label_tag(:username, "Username") %>
    <%= text_field_tag(:username, nil, :required => true) %><br>
    <%= label_tag(:password, "Password")%>
    <%= password_field_tag(:password, nil, :required => true) %><br>
    <%= submit_tag("Sign In") %>
  <% end %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spotify Calendar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container flow-text">
    <% flash.keys.each do |type| %>
    <div class="flash <%= type %>">
    <%= flash[type] %>
    <a class="close-button" href="#">X</a>
  </div>
  <% end %>
    <%= yield %>
  </body>
</html>